name: pubgrade_example
description: Sample app used to test Pubgrade against real pub.dev data.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
